options:
  gnb-ip-address:
    type: string
    default: "192.168.251.5/24"
    description: gNodeB IP Address
  gnb-interface:
    type: string
    description: Host interface to use for the RAN Network. If unspecificed, a bridge will be used.
  icmp-packet-destination:
    type: string
    default: "192.168.250.1"
    description: Default ICMP packet destination for simulation
  imsi:
    type: string
    default: "208930100007487"
    description: International Mobile Subscriber Identity
  mcc:
    type: string
    default: "208"
    description: Mobile Country Code
  mnc:
    type: string
    default: "93"
    description: Mobile Network code
  usim-key:
    type: string
    default: "5122250214c33e723a5dd523fc145fc0"
    description: USIM Key
  usim-opc:
    type: string
    default: "981d464c7c52eb6e5036234984ad0bcf"
    description: USIM Operator Key
  usim-sequence-number:
    type: string
    default: "16f3b3f70fc2"
    description: USIM sequence number
  sd:
    type: string
    default: "010203"
    description: Slice ID
  sst:
    type: int
    default: 1
    description: Slice Service Type
  tac:
    type: string
    default: "000001"
    description: Tracking Area Code. Hexadecimal value represented as a string.
  user-plane-network:
    type: string
    default: "192.168.251.0/24"
    description: User Plane Network
  user-plane-ip-address:
    type: string
    default: "192.168.251.3"
    description: IP address of the User Plane Network
  user-plane-gateway:
    type: string
    default: "192.168.251.1"
    description: Gateway to use to reach the User Plane Network
  
