name: Integration test

on:
  workflow_call:

jobs:
  integration-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup LXD
        uses: canonical/setup-lxd@main
        with:
          channel: 5.12/stable
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: 3.1/stable
          provider: microk8s
          channel: 1.27-strict/stable
          microk8s-addons: "hostpath-storage dns"
      - name: Enable Multus addon
        continue-on-error: true
        run: |
          sudo microk8s addons repo add community https://github.com/canonical/microk8s-community-addons --reference feat/strict-fix-multus
          sudo microk8s enable multus
          sudo microk8s kubectl -n kube-system rollout status daemonset/kube-multus-ds
          sudo microk8s kubectl auth can-i create network-attachment-definitions
      - name: Run integration tests
        run: tox -e integration
      - name: Archive Tested Charm
        uses: actions/upload-artifact@v3
        if: ${{ github.ref_name == 'main' }}
        with:
          name: tested-charm
          path: .tox/**/sdcore-gnbsim_ubuntu-22.04-amd64.charm
          retention-days: 5
      - name: Archive charmcraft logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: charmcraft-logs
          path: /home/runner/.local/state/charmcraft/log/*.log
      - name: Archive juju crashdump
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: juju-crashdump
          path: juju-crashdump-*.tar.xz
